version: 2
jobs:
  build:
    working_directory: ~/Kudos
    docker:
      - image: circleci/ruby:2.5.0
        environment:
          PGHOST: localhost
          PGUSER: rails
          RAILS_ENV: test
          RUN_COVERAGE: true
      - image: postgres:9.5
        environment:
          POSTGRES_USER: rails
          POSTGRES_DB: Kudos_test
          POSTGRES_PASSWORD: "password"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            sudo apt-get install nodejs

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:test:prepare

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec

  deploy:
    working_directory: ~/Kudos
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Run db migration on Heroku
          command: |
            rake db:migrate --app $HEROKU_APP_NAME
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
